-- MySQL Script generated by MySQL Workbench
-- Thu Oct 22 16:06:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customer` (
  `id` INT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(45) NOT NULL,
  `sector_activity` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `zip` CHAR(5) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `revenue` INT NOT NULL,
  `staff` INT NOT NULL,
  `phone` CHAR(10) NOT NULL,
  `comment` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project` (
  `id` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `date_start` DATE NOT NULL,
  `date_end` DATE NULL,
  `expected_date_start` DATE NOT NULL,
  `expected_date_end` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `document` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `resume` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `link` VARCHAR(45) NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`, `project_id`),
  INDEX `fk_document_project1_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_document_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `collaborator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `collaborator` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `qualification` ENUM('architecte', 'designer', 'développeur bdd', 'developpeur web', 'secrétaire bilingue', 'chef de service', 'agent commercial') NOT NULL,
  `photo` BLOB NULL,
  `adress` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `customer_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customer_project` (
  `customer_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`, `project_id`),
  INDEX `fk_customer_has_project_project1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_customer_has_project_customer_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_project_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_project_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `collaborator_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `collaborator_project` (
  `collaborator_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`collaborator_id`, `project_id`),
  INDEX `fk_collaborator_has_project_project1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_collaborator_has_project_collaborator1_idx` (`collaborator_id` ASC) VISIBLE,
  CONSTRAINT `fk_collaborator_has_project_collaborator1`
    FOREIGN KEY (`collaborator_id`)
    REFERENCES `collaborator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_collaborator_has_project_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `function`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `function` (
  `idfunction` TINYINT UNSIGNED NOT NULL,
  `function_label` ENUM('responsable etude', 'scrum master', 'developpeur', 'technicien support', 'commercial', 'technico-commercial', 'secrétaire') NOT NULL COMMENT ' Fonctions \ncollaborateur peut parfois intervenir sur un projet selon une fonction très différente ex Scrum Master ou même Commercial\n        Responsable Etude\n        Scrum Master\n        Développeur\n        Technicien support\n        Commercial\n        Technico-commercial\n        Secrétaire',
  `collaborator_id` INT UNSIGNED NOT NULL,
  `function_archive` TINYINT(1) UNSIGNED NULL,
  `project_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idfunction`),
  INDEX `fk_function_collaborator1_idx` (`collaborator_id` ASC) VISIBLE,
  CONSTRAINT `fk_function_collaborator1`
    FOREIGN KEY (`collaborator_id`)
    REFERENCES `collaborator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contract` (
  `idcontract` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `contract_start_date` DATE NOT NULL,
  `contract_end_date` DATE NULL,
  `contract_label` ENUM('initial', 'avenant') NOT NULL,
  `contract_type` ENUM('cdi', 'cdd', 'interim', 'stage') NOT NULL,
  `salary` SMALLINT UNSIGNED NOT NULL,
  `hiring_reason` VARCHAR(255) NULL,
  `collaborator_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idcontract`),
  INDEX `fk_contract_collaborator1_idx` (`collaborator_id` ASC) VISIBLE,
  CONSTRAINT `fk_contract_collaborator1`
    FOREIGN KEY (`collaborator_id`)
    REFERENCES `collaborator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contract_origin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contract_origin` (
  `idcontract_origin` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `denomination` VARCHAR(45) NOT NULL,
  `contract_idcontract` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idcontract_origin`),
  INDEX `fk_contract_origin_contract1_idx` (`contract_idcontract` ASC) VISIBLE,
  CONSTRAINT `fk_contract_origin_contract1`
    FOREIGN KEY (`contract_idcontract`)
    REFERENCES `contract` (`idcontract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
